### ISSUE TITLE
Allow to specify  service Ip to use for controlPlane

### ISSUE THREAD

**Issue by samuelbartel** [rancher-sandbox/cluster-api-provider-rke2#136]
**Describe the solution you'd like:**
Right now the [getIPAddress](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/c565c8fefe0feed1bf6774bdd73634a0fe085b23/controlplane/internal/controllers/rke2controlplane_controller.go#L737) function defined  in the rke2controlplane_controller take the first InternalIP of the machines as address to be used as the availableServerIP.

This  is is an issue when having nodes with several interfaces. Moreover with Baremetalhost the getIPAddress function get IP addresses from the machines.cluster.x-k8s.io and those addresses are the one from the introspection step of the baremetalhost.
on that case we want to  ignore addresses from the inspection for two important reasons:
-some IPs are obtained through DHCP, but when provisioning we use static IPs
-NIC names depends on the OS distribution and might differ from IPA and target OS

We have tried to use the   [advertiseAddress](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/c565c8fefe0feed1bf6774bdd73634a0fe085b23/controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml#L551) parameter from serverConfig but it has no effect

As a result we cannot control which address will be set on worker config.yaml as server and  use to join the cluster leading to wrong setup.

We should be able to specify in the serverConfig of the RKE2ControlPlane the address to be used as the AvailableServerIp and relay on an Address randomly taken on the machines

**Why do you want this feature:**
We need this feature to be able to deploy RKE2 cluster on environment with nodes with several nics

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by belgaied2** [comment]
My understanding is that:
- The `availableIpAddresses` is bubbled up from the `Machine.Status.Addresses` field, by looping through the list. If an InternalIP is found, it will be used. If no InternalIP is found  but an externalIP is found, it will be used. This in itself might be an unwanted behaviour. We need to better define the algorithm.
- The `Machine.Status.Addresses` field is taken from the infrastructure provider, whose behaviour is unknown: which addresses does the infra provider provide if there are multiple ones? in which order? Nothing can be assumed.

Questions:
- Do you imagine there might be a reason to need a dns name to register nodes and not an IP?
- Are you aware of any logic that makes it possible to select an address from the available `InfrastructureMachine.Status.Addresses` field?
- If you do use a field like `advertiseAddress`, do we assume the address is an actual address of a node ? I think this field would still be need (I don't think we should add another field) because it is probably used in the Subject Alternative Names of the CA for the registration URL: `https://<advertisedAddress>:9345`.

**Comment by richardcase** [comment]
The change has been made and will be in the next release of the provider.
