### ISSUE TITLE
Bump CAPI to latest v1.4.x

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/cluster-api-provider-rke2#169]
**Describe the solution you'd like:**
Bump the existing 0.1.x release series to CAPI 1.4.x

**Why do you want this feature:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by furkatgofurov7** [comment]
We recently bumped it to [v1.5.2](https://github.com/rancher-sandbox/cluster-api-provider-rke2/commit/8443fd0ade49c590b369520971d75f7810c3d887) (but have not releases yet a provider with newest CAPI v1.5.x support) and it was bumped to v1.4.x in https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/135 long ago but before v0.1.1 release, meaning we have at least one v0.1.x release with CAPI v1.4.x.

Should we close this issue?

**Comment by richardcase** [comment]
The original idea was to create a 0.1.x release with the CAPI 1.4.x bump.
And then create a 0.2.0 release with the CAPI 1.5.x bump.

**Comment by furkatgofurov7** [comment]
> The original idea was to create a 0.1.x release with the CAPI 1.4.x bump. And then create a 0.2.0 release with the CAPI 1.5.x bump.

@richardcase probably it is late to do it since we have merged the 1.5.x bump already to the main branch without branching out? Probably, we could start following it for the upcoming v1.6.x CAPI bump, i.e. we will branch out from the current main to release-0.1 branch to track 1.5.x CAPI, bump CAPI to 1.6.x in main and branch out from it to release-0.2 branch, all the newest and latest code will be on main.

**Comment by richardcase** [comment]
I agree @furkatgofurov7 . Unless we retrospectively create the release branch it seems like we don't need this.

100% agree that we need to start using release branches. CAPI 1.5.x will do into the 0.2.0 release, so we can create the release-0.2 branch as part of that.

**Comment by richardcase** [comment]
Based on ^^^ lets close
